version: '2'

services:
  app:
    build:
      context: .
    container_name: pastebin
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pastebin?currenSchema=pastebin
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - '8080:8080'

  db:
    image: postgres:16.0-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pastebin
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    command: server /data --console-address :9090
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - ~/minio/data:/data