version: '3'

networks:
  pastebin:
    driver: bridge

services:
  app:
    build:
      context: .
    container_name: pastebin
    networks:
      - pastebin
    depends_on:
      - db
      - minio
    env_file:
      - .env
    ports:
      - '8080:8080'

  db:
    image: postgres:16.0-alpine
    container_name: postgres
    networks:
      - pastebin
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d

  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - pastebin
    restart: always
    command: server /data --console-address :9090
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - ~/minio/data:/data