spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}?currenSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
  main:
    allow-circular-references: true
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: pastebin
  config:
    import: optional:file:.env[.properties]
jwt:
  secret: ${JWT_SECRET}
  lifetime: 10m
minio:
  bucket: ${MINIO_BUCKET}
  endpoint: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
springdoc:
  override-with-generic-response: false