server:
  port: 8189
  servlet:
    context-path: /demo
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 10m
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pastebin?currenSchema=pastebin
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  main:
    allow-circular-references: true