server:
  port: 8189
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 10m
minio:
  bucket: notes
  endpoint: http://192.168.0.147:9000
  accessKey: Vfl5mDybCsAnilA3a7Vx
  secretKey: bs3VjEepJPcry9d35HengWsetEu80jUQKMajs6ze
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pastebin?currenSchema=pastebin
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  main:
    allow-circular-references: true
springdoc:
  override-with-generic-response: false