name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: application.yaml
          path: /src/main/resources/application.yaml
      - name: Package app
        run: mvn package -DskipTests