name: Test application
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Java
        run: apt install openjdk-17-jdk
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Test app
        run: mvn test